stages:
  - build
  - test

#Add the style checker in build_job

build-job:
  stage: build
  image: python:3.11
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
  after_script:
    - echo "(Gitlab) Build job finished!"

test-job1:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - output=$(python3 app/api/test_unittest.py)
    - docker compose up --build
    - echo "$output"
  retry: 2
  after_script:
    - echo "(Gitlab) Test Job 1 finished!"

