stages:
  - build
  - test

build-job:
  stage: build
  image: python:3.11
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - pip install -r requirements.txt
  retry: 
  after_script:
    - echo "(Gitlab) Build job finished!"

test-job1:
  stage: test
  image: python:3.11
  script:
    - output=$(python3 tester.py)
    - echo "$output"
    - echo "$output" | grep -qE "Cache miss! Fetching resume text from PDF.|Cache hit! Missing skills found in Redis." || exit 1
  retry: 2
  after_script:
    - echo "(Gitlab) Test Job 1 finished!"

