stages:
  - build
  - test
  - deploy


build-job:
  stage: build
  image: python:3.11
  script:
    - python -m venv venv
    - venv/bin/pip install -r requirements.txt
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - venv/bin/flake8 > style_logs.txt
  allow_failure: true
  after_script:
    - echo "(Gitlab) Build job finished!"

test-job1:
  stage: test
  image: python:3.11
  script:
    - source app/api/venv/bin/activate
    - pip install -r requirements.txt
    - cd ../..
    - pytest
  retry: 2
  after_script:
    - echo "(Gitlab) Test Job 1 finished!"

deploy_job:
  stage: deploy
  image: python:3.11
  script:
    - docker compose up --build